### ISSUE TITLE
Install script does not install BSON correctly on a fresh Ubuntu install

### ISSUE THREAD

**Issue by Hoolean** [Stansbridge/untangled-2017#24]
```
Traceback (most recent call last):
  File "./client.py", line 210, in <module>
    g.run()
  File "./client.py", line 150, in run
    self.network.node.shout("world:position", bson.dumps(me.get_position()._asdict()))
AttributeError: module 'bson' has no attribute 'dumps'
```

This error is given, seemingly indicating that `bson` has not installed correctly or is not at the latest version.

**Comment by Hoolean** [comment]
Issue fixed as of 2975a4ac68838bd3ebc0c792b453bbfbe09d9bcd by preventing the script from being run with sudo unless the user is more assertive.

Please reopen the issue if this fix doesn't work for other people.
